<?xml version="1.0" encoding="utf-8" ?>
<DUMMY>
  <!-- Our theme includes -->
  <!-- Main components -->
  <INCLUDE_ONCE file="$THEME_PATH$/decorations/decorations.inc"/>
	<INCLUDE_ONCE file="$THEME_PATH$/toolbar/toolbar.inc" />
	<INCLUDE_ONCE file="$THEME_PATH$/titlebar/titlebar.inc"/>
	
	<!-- Widgets -->
	<INCLUDE_ONCE file="$THEME_PATH$/knobs/knobs.inc" />
	<INCLUDE_ONCE file="$THEME_PATH$/round_meter/round_meter.inc" />
	<INCLUDE_ONCE file="$THEME_PATH$/settings_buttons/settings_buttons.inc" />
  <INCLUDE_ONCE file="$THEME_PATH$/buttons/buttons.inc" />
  <INCLUDE_ONCE file="$THEME_PATH$/switches/switches.inc" />

  <!-- Other Utilities -->
	<INCLUDE_ONCE file="$THEME_PATH$/utils/tpl.image_opacity_box.inc"/>
</DUMMY>