<?xml version="1.0" encoding="utf-8" ?>
<DUMMY>
  <TEMPLATE id="TPL_ROUND_METER" param_id="#UNDEFINED#" positions_count="127">
      <COLUMN v_margin="-18">
        <CELL height="18"/>
        <IMAGE_PARAM_METER param_id="$param_id$" image="$THEME_PATH$/round_meter/round_meter.png" images_count="127" positions_count="$positions_count$"  ignore_mask_files="true"/>
      </COLUMN>
  </TEMPLATE>
</DUMMY>