<?xml version="1.0" encoding="utf-8" ?>
<DEFINE>
    <CUS_HMETER base_type="IMAGE_PARAM_LINEAR_METER" orientation="horizontal" image="hmeter/hmeter_long.png" ignore_mask_files="true"/>
    <CUS_HMETER_LONG base_type="IMAGE_PARAM_LINEAR_METER" orientation="horizontal" image="hmeter/hmeter_long.png" ignore_mask_files="true"/>
    <CUS_HMETER_BLUE base_type="IMAGE_PARAM_LINEAR_METER" orientation="horizontal" image_selected="hmeter/hmeter_long_selected_blue.png" image="hmeter/hmeter_long_bg.png" ignore_mask_files="true"/>
    <CUS_HMETER_RED base_type="IMAGE_PARAM_LINEAR_METER" orientation="horizontal" image_selected="hmeter/hmeter_long_selected_red.png" image="hmeter/hmeter_long_bg.png" ignore_mask_files="true"/>
    <CUS_HMETER_GREEN base_type="IMAGE_PARAM_LINEAR_METER" orientation="horizontal" image_selected="hmeter/hmeter_long_selected_green.png" image="hmeter/hmeter_long_bg.png" ignore_mask_files="true"/>
    <CUS_HMETER_HOLD base_type="IMAGE_PARAM_LINEAR_METER" orientation="horizontal" thumb_image="hmeter/hold_thumb.bmp" width="100%" ignore_mask_files="true"/>
</DEFINE>