<?xml version="1.0" encoding="utf-8" ?> 
<DEFINE>
    <CUS_VMETER base_type="IMAGE_PARAM_LINEAR_METER" orientation="vertical" image="vmeter/vmeter_long.png" ignore_mask_files="true"/>
    <CUS_VMETER_LONG base_type="IMAGE_PARAM_LINEAR_METER" orientation="vertical" image="vmeter/vmeter_long.png" ignore_mask_files="true"/>
    <CUS_VMETER_BLUE base_type="IMAGE_PARAM_LINEAR_METER" orientation="vertical" image="vmeter/vmeter_blue.png" ignore_mask_files="true"/>
    <CUS_VMETER_HOLD base_type="IMAGE_PARAM_LINEAR_METER" orientation="vertical" thumb_image="vmeter/hold_thumb.bmp" height="100%" ignore_mask_files="true"/>
</DEFINE>