<?xml version="1.0" encoding="utf-8" ?>
<DUMMY>
  <DEFINE>
    <!-- toolbar buttons -->
    <CUS_SHOW_CONTROLS_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$THEME_PATH$/buttons/show_controls_button.png" image_focus="$THEME_PATH$/buttons/show_controls_button_hover.png" cursor="system::hand"/>
    <CUS_SHOW_GRAPH_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$THEME_PATH$/buttons/show_graph_button.png" image_focus="$THEME_PATH$/buttons/show_graph_button_hover.png" cursor="system::hand"/>
    <CUS_SHOW_METERS_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$THEME_PATH$/buttons/show_meters_button.png" image_focus="$THEME_PATH$/buttons/show_meters_button_hover.png" cursor="system::hand"/>
    <CUS_MAGNIFY_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$THEME_PATH$/buttons/magnifier_button.png" image_focus="$THEME_PATH$/buttons/magnifier_button_hover.png" cursor="system::hand"/>
    <CUS_REFRESH_PARAM_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$THEME_PATH$/buttons/refresh_button.png" image_focus="$THEME_PATH$/buttons/refresh_button_hover.png" cursor="system::hand" images_count="1" positions_count="2"/>
    <CUS_EDIT_ACTION_BUTTON base_type="IMAGE_ACTION_BUTTON" image="$THEME_PATH$/buttons/edit_button.png" image_focus="$THEME_PATH$/buttons/edit_button_hover.png" cursor="system::hand"/>
    <CUS_FOLDER_ACTION_BUTTON base_type="IMAGE_ACTION_BUTTON" image="$THEME_PATH$/buttons/folder_button.png" image_focus="$THEME_PATH$/buttons/folder_button_hover.png" cursor="system::hand"/>

    <!-- standard icon buttons -->
    <CUS_ON_OFF_BUTTON base_type="IMAGE_PARAM_BUTTON" image="$THEME_PATH$/buttons/on_off_button.png" image_focus="$THEME_PATH$/buttons/on_off_button_hover.png" cursor="system::hand"/>
    <CUS_CHECK_BOX base_type="IMAGE_PARAM_BUTTON" image="$THEME_PATH$/buttons/check_box.bmp" image_orientation="horizontal" cursor="system::hand"/>
    
    <!-- Buttons that may be used to include text -->
    <CUS_STATUS_BUTTON_80 base_type="IMAGE_PARAM_BUTTON" image="$THEME_PATH$/buttons/status_rect_button80.png" image_focus="$THEME_PATH$/buttons/status_rect_button80_hover.png" cursor="system::hand"/>
    
    <CUS_DROPDOWN_PARAM_BUTTON_90 base_type="IMAGE_PARAM_MENU_BUTTON" image="$THEME_PATH$/buttons/dropdown90.png" image_focus="$THEME_PATH$/buttons/dropdown90_hover.png" cursor="system::hand"/>
     
     <CUS_DROPDOWN_ACTION_BUTTON_90 base_type="IMAGE_ACTION_BUTTON" image="$THEME_PATH$/buttons/dropdown90.png" image_focus="$THEME_PATH$/buttons/dropdown90_hover.png" cursor="system::hand"/>

    <CUS_DROPDOWN_PARAM_BUTTON_80 base_type="IMAGE_PARAM_MENU_BUTTON" image="$THEME_PATH$/buttons/dropdown80.png" cursor="system::hand"/>
     
     <CUS_DROPDOWN_ACTION_BUTTON_80 base_type="IMAGE_ACTION_BUTTON" image="$THEME_PATH$/buttons/dropdown80.png" cursor="system::hand"/>
     
 
  </DEFINE>
</DUMMY>